WebCompany.UI/Areas/Admin/Controllers/SliderController.cs
using System;
using System.Web;
using System.Web.Mvc;
using WebCompany.Core;
using WebCompany.Data;
using WebCompany.Services; 
using WebCompany.UI.Models;

namespace WebCompany.UI.Areas.Admin.Controllers
{
    public class SliderController : Controller
    {
        private ISliderService sliderService;
        private readonly ILanguageService languageService;
        public SliderController(
        ISliderService sliderService,
        ILanguageService languageService
        )
        {
            this.sliderService = sliderService;
            this.languageService = languageService;
        }
        public ActionResult List()
        {
            var model = new SiteModel();
            model.SliderListModel = sliderService.GetSliderList();
            return View(model);
        }

        public ActionResult Create()
        {
            var model = new SiteModel();
            model.SliderModel = new SliderDto();
            model.SliderModel.ContentId = Guid.NewGuid();
            model.SliderModel.LanguageId = 1;
            return View(model);

        }
        public ActionResult Edit(Guid Id)
        {
            var model = new SiteModel();
            model.SliderListModel = sliderService.GetSliderListByContentId(Id);
            model.LanguageListModel = languageService.GetLanguageList();
            return View(model);
        }
        public ActionResult Delete(int Id)
        {
            var slider = sliderService.GetSliderId(Id);
            sliderService.Delete(slider);
            TempData["Result"] = true;
            TempData["Message"] = "Kayıt başarılı bir şekilde silinmiştir";
            return Redirect("/admin/slider/List");
        }

        public ActionResult Save(SiteModel model, HttpPostedFileBase file)
        {
             
            if (ModelState.IsValid)
            {

                string sliderPath = UrlExtensions.ProductNotFound;
                if (file != null)
                {
                    var imageConfig = new Config()
                    {
                        FileBase = file,
                        FileName = file.FileName,
                        Width = UrlExtensions.SliderImageWidth,
                        ImagePath = UrlExtensions.SliderImagePath,
                        ContentName = model.SliderModel.Name
                    };
                    sliderPath = ImageUpload.ImgUploadGaleri(imageConfig); 

                }

                if (model.SliderModel.Id == 0)
                {

                    model.SliderModel.CreatedDateTime = DateTime.Now;
                    model.SliderModel.UpdateDateTime = DateTime.Now;
                    model.SliderModel.Image = sliderPath;
                    sliderService.Insert(model.SliderModel);
                    ModelState.Clear();
                    TempData["Result"] = true;
                    TempData["Message"] = "Kayıt başarılı bir şekilde eklenmiştir";
                    return Redirect(UrlService.AdminGetUrl("slider/List"));
                }
                else
                {

                    model.SliderModel.CreatedDateTime = DateTime.Now;
                    model.SliderModel.UpdateDateTime = DateTime.Now;
                    model.SliderModel.Image = file != null ? sliderPath:model.SliderModel.Image;
                    sliderService.Update(model.SliderModel);
                    ModelState.Clear();
                    TempData["Result"] = true;
                    TempData["Message"] = "Kayıt başarılı bir şekilde güncellemiştir";
                    return Redirect(UrlService.AdminGetUrl("slider/List"));
                }
            }
            return View(model.SliderModel.Id == 0 ? "Create" : "Edit");

        }
    }
}

WebCompany.UI/Areas/Admin/Views/Slider/Create.cshtml
@model WebCompany.UI.Models.SiteModel
@{
    ViewBag.Title = "Haber ekle";
}
<div class="span9" id="content">
    <div class="row-fluid">

        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Slider Ekle</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    @Html.Partial("_CreateOrEdit", Model);
                </div>
            </div>
        </div>
    </div>

</div>

WebCompany.UI/Areas/Admin/Views/Slider/Edit.cshtml
@model WebCompany.UI.Models.SiteModel
@{
    ViewBag.Title = "Slider Düzenle";
}
<div class="span9" id="content">
    <div class="row-fluid">

        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Slider Düzenle</div>
            </div>


            <div class="block-content collapse in">
                <div class="span12">

                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        @foreach (var lan in Model.LanguageListModel)
                        {
                            <li class="nav-item @(Model.LanguageListModel.IndexOf(lan)==0?"active":"")">
                                <a class="nav-link active" id="@(lan.Symbol)-tab" data-toggle="tab" href="#@(lan.Symbol)" role="tab" aria-controls="@(lan.Symbol)" aria-selected="true">@(lan.Title)</a>
                            </li>
                        }
                    </ul>
                    <div class="tab-content" style="display:block">
                        @foreach (var _model in Model.LanguageListModel)
                        {
                            {

                                Model.SliderModel = Model.SliderListModel.FirstOrDefault(d => d.LanguageId == _model.Id);
                                if (Model.SliderModel == null)
                                {
                                    var slider = new WebCompany.Data.SliderDto();
                                    slider.ContentId = Model.SliderListModel.FirstOrDefault().ContentId;
                                    slider.LanguageId = _model.Id;
                                    Model.SliderModel = slider;
                                }
                            }
                            <div class="tab-pane @(Model.LanguageListModel.IndexOf(_model)==0?"active":"")" id="@(_model.Symbol)" role="tabpanel" aria-labelledby="@(_model.Symbol)-tab">

                                @Html.Partial("_CreateOrEdit", Model)
                            </div>

                        }
                    </div>
                </div>
            </div>

        </div>
    </div>

</div>

WebCompany.UI/Areas/Admin/Views/Slider/List.cshtml
@model  WebCompany.UI.Models.SiteModel

@{
    ViewBag.Title = "Sayfa";
}



<style>
    .validation-summary-errors {
        background-color: #D9FFB2;
        border: 1px solid #5CBA30;
        width: 400px;
    }
</style>


<div class="span9" id="content">

    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Slider Listesi</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <div class="table-toolbar">
                        <div class="btn-group">
                            <a href="@WebCompany.Core.UrlService.AdminGetUrl("Slider/Create")">
                                <button class="btn btn-success">Slider Ekle  <i class="icon-plus icon-white"></i></button>
                            </a>
                        </div> 
                    </div>

                    @if (TempData["Message"] != null)
                     {<div class="@Html.Raw(Convert.ToBoolean(TempData["Result"])==true? "alert alert-success":"alert alert-error")">
                        <button class="close" data-dismiss="alert">×</button>
                        <strong>@Html.Raw(Convert.ToBoolean(TempData["Result"]) == true ? "Success!" : "Error!")</strong>@TempData["Message"]
                    </div>}
                    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example2">
                        <thead>
                            <tr> 
                                <th>Başlık</th>  
                                <th>Image</th> 
                                <th>Sıra</th>
                                <th>Durum</th>
                                <th>İşlem</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var Item in Model.SliderListModel.Where(f=> f.LanguageId==1))
                            {
                                <tr class="odd gradeX">
                                  
                                    <td>@Item.Name</td> 
                                    <td><img src="@WebCompany.Core.UrlService.ImagePathHomeView(WebCompany.Core.UrlExtensions.SliderViewPath,"mobile",Item.Image)" width="720px" height="52px" /></td>
                                    <td>@Item.Rows</td> 
                                    <td>@Html.Raw(Item.Actived == true ? "<span class='label label-success'>Onayli</span>" : "<span class='label label-important'>Onaysız</span>")</td>
                                    <td class="center" style="width:75px;">
                                        <a href="@WebCompany.Core.UrlService.AdminGetUrl("slider/delete/"+@Item.Id)" class="btn btn-danger btn-mini">Sil</a>
                                        <a href="@WebCompany.Core.UrlService.AdminGetUrl("slider/edit/"+@Item.ContentId)" class="btn btn-success btn-mini">Düzelt</a>
                                    </td>

                                </tr>
                            }
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
</div>

WebCompany.UI/Areas/Admin/Views/Slider/_CreateOrEdit.cshtml
@model WebCompany.UI.Models.SiteModel

@{
    ViewBag.Title = "İçerikler";
}


                    @using (Html.BeginForm("Save", "Slider", FormMethod.Post, new { id = "frmSite", @class = "form-horizontal", enctype = "multipart/form-data" }))
                    {
                        @Html.ValidationSummary()
                        if (Model != null && Model?.SliderModel != null)
                        {
                    <fieldset>
                       
                            
                            @if (Model == null || Model.SliderModel.Id == null)
                            {
                                <div class="controls">@Html.HiddenFor(m => m.SliderModel.Id, new { @class = "input-xlarge focused", @readonly = "readonly", Value = "0" })</div>
                            }
                            else
                            {
                                <div class="controls">@Html.HiddenFor(m => m.SliderModel.Id, new { @class = "input-xlarge focused", @readonly = "readonly" })</div>
                            }
                     
                        <div class="control-group">
                            <label class="control-label" for="focusedInput">Fotoğraf boyutu</label>
                            <div class="controls" style="font-weight:bolder;">En az @WebCompany.Core.UrlExtensions.SliderImageWidth.Split(',').LastOrDefault() px genişlik</div>
                        </div>
                        <span></span>
                        <div class="control-group">
                            <label class="control-label" for="focusedInput">@Html.LabelFor(m => m.SliderModel.Name)</label>
                            <div class="controls">@Html.TextBoxFor(m => m.SliderModel.Name, new { @class = "input-xlarge focused", @placeholder = "Başlık..." })  </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="focusedInput">@Html.LabelFor(m => m.SliderModel.Url)</label>
                            <div class="controls">
                                @Html.TextBoxFor(m => m.SliderModel.Url, new { @class = "input-xlarge focused", @placeholder = "Url..." })
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="focusedInput">@Html.LabelFor(m => m.SliderModel.Title)</label>
                            <div class="controls">
                                @Html.TextBoxFor(m => m.SliderModel.Title, new { @class = "input-xlarge focused", @placeholder = "Başlık..." })
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="focusedInput">@Html.LabelFor(m => m.SliderModel.ShortDetail)</label>
                            <div class="controls">
                                @Html.TextBoxFor(m => m.SliderModel.ShortDetail, new { @class = "input-xlarge focused", @placeholder = "Detay..." })
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="focusedInput">@Html.LabelFor(m => m.SliderModel.Rows)</label>
                            <div class="controls">
                                @Html.TextBoxFor(m => m.SliderModel.Rows, new { @class = "input-xlarge focused",@type="number", @placeholder = "Sıra..." })
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="focusedInput">@Html.LabelFor(m => m.SliderModel.Image)</label>

                            <div class="controls">
                                <input type="file" name="file" id="file" />
                                @Html.HiddenFor(m => m.SliderModel.Image)
                                @Html.HiddenFor(m => m.SliderModel.LanguageId)
                                @Html.HiddenFor(m => m.SliderModel.ContentId)
                            </div>
                            <br />
                            <div class="controls"><img src="@WebCompany.Core.UrlService.ImagePathHomeView(WebCompany.Core.UrlExtensions.SliderViewPath, "mobile", Model.SliderModel.Image)" width="110px" height="52px" /></div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="focusedInput">@Html.LabelFor(m => m.SliderModel.Actived)</label>
                            <div class="controls">@Html.CheckBox("SliderModel.Actived") </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary">Kaydet</button>
                            <button type="reset" class="btn">Vazgeç</button>
                        </div>
                    </fieldset>
                            }
                        }

               