WebCompany.UI/Areas/Admin/Controllers/MenuController.cs
using System;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using WebCompany.Business.Models;
using WebCompany.Core;
using WebCompany.Data;
using WebCompany.Services;

namespace WebCompany.UI.Areas.Admin.Controllers
{
    public class MenuController : Controller
    {
        private readonly IMenuService menuService;
        private readonly IUrlsService urlsService;
        private readonly ILanguageService languageService;
        public MenuController(
        IMenuService menuService,
        IUrlsService urlsService,
        ILanguageService languageService)
        {
            this.menuService = menuService;
            this.urlsService = urlsService;
            this.languageService = languageService;
        }
        public ActionResult List()
        {
            //var model = new SiteModel();
            //model.MenuListModel= menuService.GetMenuList(); 
            //return View(model);
            var result = menuService.GetMenuList().OrderBy(x => x.Rows).ToList();

            string menu = "";
            foreach (var item in result.Where(x => x.MenuTop == 0))
            {
                menu += string.Format("<li>{1} - <a href=" + UrlService.AdminGetUrl("Menu/Create/{0}") + ">Ekle</a>", item.Id, item.MenuUrl.Title);
                menu += string.Format("| <a href=" + UrlService.AdminGetUrl("Menu/Edit/{0}") + ">Düzelt</a> ", item.Id);
                menu += string.Format(" | <a href=" + UrlService.AdminGetUrl("Menu/Delete/{0}") + ">Sil</a></li>", item.Id);

                menu += SubCategoryService(item.Id);

            }
            ViewBag.Tree = menu;
            return View();
        }
        public ActionResult Create(int Id = 0)
        {
            var model = new MenuCreateViewModel();
            model.Menu.MenuTop = 0;
            ModelState.Clear();
            if (Id != 0)
            {
                var menuservice = menuService.GetMenuId(Id);
                model.Menu.Id = 0;
                model.Menu.MenuTop = Id; 
            }

            var urlModel= urlsService.GetUrlList(); 
            model.Urls = urlModel.ToList();
            model.Menu.Id = 0; 
            model.Menu.MenuTop = Id; 
            return View(model);
        }
        public ActionResult Edit(int id)
        {
            var model = new MenuCreateViewModel();
            var menus = menuService.GetMenuId(id);
            model.Menu = GetMenuDtoModel(menus);  
            model.Urls = urlsService.GetUrlList();
            return View("Edit", model);

        }
        public ActionResult Delete(int id)
        {
            var modelResult = menuService.GetMenuId(id);

            menuService.Delete(modelResult);
            TempData["Message"] = "Menü alanı silinmiştir";
            TempData["Result"] = true;
            return Redirect(UrlService.AdminGetUrl("Menu/List"));
        }
        public ActionResult Save(MenuCreateViewModel models)
        {

            if (ModelState.IsValid)
            {
                var model = GetMenusModel(models.Menu);

                if (model.Id == 0)
                {
                    model.CreatedDateTime = DateTime.Now;
                    model.UpdateDateTime = DateTime.Now;  
                   
                    menuService.Insert(model);
                    ModelState.Clear();
                    TempData["Result"] = true;
                    TempData["Message"] = "Kayıt başarılı bir şekilde eklenmiştir";
                    return Redirect(UrlService.AdminGetUrl("menu/List"));  

                }
                else
                {

                    var menu = menuService.GetMenuId(model.Id);
                    menu.Name = models.Menu.Name;
                    menu.Rows = models.Menu.Rows;
                    menu.UpdateDateTime = DateTime.Now; 
                    menu.Actived = models.Menu.Actived;
                    menu.UrlId = models.Menu.UrlId;
                    menuService.Update(menu);
                    ModelState.Clear();
                    TempData["Result"] = true;
                    TempData["Message"] = "Kayıt başarılı bir şekilde eklenmiştir";

                    return Redirect(UrlService.AdminGetUrl("menu/List"));


                }

            }   
            return View(models.Menu.Id == 0 ? "Create" : "Edit", models);
        }
        public MenuDto GetMenusModel(MenuViewModel menuModel)
        {

            var model = new MenuDto()
            {
                Id = menuModel.Id,
                Name = menuModel.Name,
                MenuTop = menuModel.MenuTop, 
                Rows = menuModel.Rows,
                //Url = menuModel.Url,
                Actived = menuModel.Actived,
                Deleted = menuModel.Deleted, 
                CompanyId=menuModel.CompanyId,
                UrlId=menuModel.UrlId, 
            };

            return model;
        }
        public MenuViewModel GetMenuDtoModel(MenuDto menuModel)
        {

            var model = new MenuViewModel()
            {
                Id = menuModel.Id,
                Name = menuModel.Name,
                MenuTop = menuModel.MenuTop, 
                Rows = menuModel.Rows,
                //Url = menuModel.Url,
                Actived = menuModel.Actived,
                Deleted = menuModel.Deleted,
                CompanyId=menuModel.CompanyId, 
                UrlId=menuModel.UrlId
            };

            return model;
        }

       
        public string SubCategoryService(int Id)
        {
            var menuservis = menuService.GetMenuList().Where(x => x.MenuTop == Id);
            StringBuilder str = new StringBuilder();
            if (menuservis.Count() != 0)
            {

                str.Append("<ul>");
                foreach (var item in menuservis)
                {
                    str.Append(string.Format("<li>{0}", item.MenuUrl.Title));
                    
                        str.Append(string.Format("<a href=" + UrlService.AdminGetUrl("Menu/Create/{0}") + ">Ekle</a>", item.Id));
                        str.Append(string.Format("| <a href=" + UrlService.AdminGetUrl("Menu/Edit/{0}") + ">Düzelt</a>", item.Id));
                        str.Append(string.Format(" | <a href=" + UrlService.AdminGetUrl("Menu/Delete/{0}") + "> Sil</a></li>", item.Id));

                    
                    str.Append(SubCategoryService(item.Id));
                }
                str.Append("</ul>");
            }

            return str.ToString();
        }
    }
}

WebCompany.UI/Areas/Admin/Views/Menu/Create.cshtml
@model WebCompany.UI.Models.MenuCreateViewModel
@{
    ViewBag.Title = "Menü ekle";
}

<div class="span9" id="content">
    <div class="row-fluid">

        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Menü Ekle</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    @Html.Partial("_CreateOrEdit", Model);
                </div>
            </div>
        </div>
    </div>

</div>

WebCompany.UI/Areas/Admin/Views/Menu/Edit.cshtml
@model WebCompany.UI.Models.MenuCreateViewModel
@{
    ViewBag.Title = "Menü Düzelt";
}
<div class="span9" id="content">
    <div class="row-fluid">

        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Menü Duzelt</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    @Html.Partial("_CreateOrEdit", Model);
                </div>
            </div>
        </div>
    </div>

</div>

WebCompany.UI/Areas/Admin/Views/Menu/List.cshtml
@model  WebCompany.UI.Models.MenuViewModel

@{
    ViewBag.Title = "Menü Ekle";
}



<style>
    .validation-summary-errors {
        background-color: #D9FFB2;
        border: 1px solid #5CBA30;
        width: 400px;
    }
</style>


<div class="span9" id="content">

    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Menu Listesi</div>
            </div>
            <a href="@WebCompany.Core.UrlService.AdminGetUrl("Menu/Create/0")"><button class="btn btn-success">Menü Ekle<i class="icon-plus icon-white"></i></button></a>
            <div class="block-content collapse in">
                <div class="span12"> 
                    <ul id="menu">
                        <div>
                            <p>Menü Listesi</p>
                            <ul class="tree">
                                @Html.Raw(ViewBag.Tree) 
                            </ul>
                        </div> 
                    </ul>
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
</div>
<style>
    .tree,
    .tree ul {
        margin: 0 0 0 1em; /* indentation */
        padding: 0;
        list-style: none;
        color: #369;
        position: relative;
    }

        .tree ul {
            margin-left: .5em;
        }
            /* (indentation/2) */

            .tree:before,
            .tree ul:before {
                content: "";
                display: block;
                width: 0;
                position: absolute;
                top: 0;
                bottom: 0;
                left: 0;
                border-left: 1px solid;
            }

        .tree li {
            margin: 0;
            padding: 0 1.5em; /* indentation + .5em */
            line-height: 2em; /* default list item's `line-height` */
            font-weight: bold;
            position: relative;
        }

            .tree li:before {
                content: "";
                display: block;
                width: 10px; /* same with indentation */
                height: 0;
                border-top: 1px solid;
                margin-top: -1px; /* border top width */
                position: absolute;
                top: 1em; /* (line-height/2) */
                left: 0;
            }

            .tree li:last-child:before {
                background: white; /* same with body background */
                height: auto;
                top: 1em; /* (line-height/2) */
                bottom: 0;
            }
</style>

WebCompany.UI/Areas/Admin/Views/Menu/_CreateOrEdit.cshtml
@model WebCompany.UI.Models.MenuCreateViewModel

@{
                /**/

                ViewBag.Title = "Menü Ekle";
}


@using (Html.BeginForm("Save", "Menu", FormMethod.Post, new { id = "frmSite", @class = "form-horizontal" }))
{
    @Html.ValidationSummary()
    <fieldset>
        <div class="control-group">
             
            @if (Model == null || Model.Menu.Id == null)
            {
                @Html.HiddenFor(m => m.Menu.Id, new { @class = "input-xlarge focused", @readonly = "readonly", Value = "0" }) 
            }
            else
            {
                @Html.HiddenFor(m => m.Menu.Id, new { @class = "input-xlarge focused", @readonly = "readonly" }) 
            }
      
        @*<div class="control-group">
            <label class="control-label" for="focusedInput">@Html.LabelFor(m => m.Menu.Name)</label>*@
            <div class="controls">@Html.HiddenFor(m => m.Menu.Name, new { @class = "input-xlarge focused", @placeholder = "Menü Adı..." ,@value=""})  </div>
        @*</div>*@




        <div class="control-group">
            <label class="control-label" for="focusedInput">@Html.LabelFor(m => m.Menu.Rows)</label>
            <div class="controls">@Html.TextBoxFor(m => m.Menu.Rows, new { @class = "input-xlarge focused" , @type = "number", @placeholder = "Sıra..." })  </div>
        </div>
        @Html.HiddenFor(m => m.Menu.MenuTop) 

        <div class="control-group">
            <label class="control-label" for="focusedInput">@Html.LabelFor(m => m.Urls)</label>
            <div class="controls">
                <select name="Menu.UrlId" id="Menu.UrlId">
                    
                    @foreach (var url in Model.Urls)
                    {
                        <option value="@url.Id">@url.Title</option>
                    }

                </select>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="focusedInput">@Html.LabelFor(m => m.Menu.Actived)</label>
            <div class="controls">@Html.CheckBox("Menu.Actived") </div>
        </div>
        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Kaydet</button>
            <button type="reset" class="btn">Vazgeç</button>
        </div>
        <div class="alert-info"><span>İletişim</span>sayfası için url:iletisim, Blog sayfası için url:blog yazmanız yeterli</div>
    </fieldset>
}