WebCompany.UI/Areas/Admin/Controllers/UrlsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebCompany.Core;
using WebCompany.Data;
using WebCompany.Services;
using WebCompany.UI.Models;

namespace WebCompany.UI.Areas.Admin.Controllers
{
    public class UrlsController : Controller
    {
        // GET: Admin/Urls
        #region Members
        private readonly IUrlsService urlsService;
        private readonly ILanguageService languageService;
        #endregion
        #region Ctr
        public UrlsController(IUrlsService urlsService, ILanguageService languageService)
        {
            this.urlsService = urlsService;
            this.languageService = languageService;
        }
        #endregion
        public ActionResult List()
        {
            var model = new SiteModel();
            model.UrlsModelList = urlsService.GetUrlList();
            return View(model);
        }
        public ActionResult Create()
        {
            var model = new SiteModel();
            var urls = new UrlsDto();
            urls.ContentId = Guid.NewGuid();
            urls.LanguageId = 1;
            model.UrlsModel = urls;
            return View(model);
        }
        public ActionResult Edit(Guid Id)
        {
            var model = new SiteModel();

            model.UrlsModelList = urlsService.GetUrlListByContentId(Id);
            model.LanguageListModel = languageService.GetLanguageList();
            return View(model);
        }
        public ActionResult Delete(int Id)
        {
            var urls = urlsService.GetUrBylId(Id);
            urlsService.Delete(urls);
            TempData["Result"] = true;
            TempData["Message"] = "Kayıt başarılı bir şekilde silinmiştir";
            return Redirect(UrlService.AdminGetUrl("urls/List"));
        }
        [ValidateInput(false)]
        public ActionResult Save(SiteModel model)
        {

            if (ModelState.IsValid)
            {
 
                if (model.UrlsModel.Id == 0)
                {
                    model.UrlsModel.CreatedDateTime = DateTime.Now;
                    model.UrlsModel.UpdateDateTime = DateTime.Now;
                    model.UrlsModel.Type =true;
                    model.UrlsModel.Deleted = false;
                    urlsService.Insert(model.UrlsModel);
                    ModelState.Clear();
                    TempData["Result"] = true;
                    TempData["Message"] = "Kayıt başarılı bir şekilde eklenmiştir";
                }
                else
                {
                    var urls = urlsService.GetUrBylId(model.UrlsModel.Id);

                    urls.UpdateDateTime = DateTime.Now;
                    urls.Title = model.UrlsModel.Title;
                    urls.ContentId = model.UrlsModel.ContentId;
                    urls.LanguageId = model.UrlsModel.LanguageId;
                    urls.Url = model.UrlsModel.Url;
                    urls.Type = true;
                    urls.Deleted = false;
                    urls.Actived = model.UrlsModel.Actived;
                    urlsService.Update(urls);
                    ModelState.Clear();

                    TempData["Result"] = true;
                    TempData["Message"] = "Kayıt başarılı bir şekilde güncellenmiştir";
                }
                return Redirect(UrlService.AdminGetUrl("urls/List"));
            }
            return View(model.UrlsModel.Id == 0 ? "Create" : "Edit", model);
        }

    }
}

WebCompany.UI/Areas/Admin/Views/Urls/Create.cshtml
@model WebCompany.UI.Models.SiteModel
@{
    ViewBag.Title = "Menü Url Ekle";
}

<div class="span9" id="content">
    <div class="row-fluid">

        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Menü Url Ekle</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    @Html.Partial("_CreateOrEdit", Model);
                </div>
            </div>
        </div>
    </div>

</div>

WebCompany.UI/Areas/Admin/Views/Urls/Edit.cshtml
@model  WebCompany.UI.Models.SiteModel
@{
    ViewBag.Title = "Menu Url Düzelt";
}
 
<div class="span9" id="content">
    <div class="row-fluid">

        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Menü Url Düzenle</div>
            </div>


            <div class="block-content collapse in">
                <div class="span12">

                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        @foreach (var lan in Model.LanguageListModel)
                        {
                            <li class="nav-item @(Model.LanguageListModel.IndexOf(lan)==0?"active":"")">
                                <a class="nav-link active" id="@(lan.Symbol)-tab" data-toggle="tab" href="#@(lan.Symbol)" role="tab" aria-controls="@(lan.Symbol)" aria-selected="true">@(lan.Title)</a>
                            </li>
                        }
                    </ul>
                    <div class="tab-content" style="display:block">
                        @foreach (var _model in Model.LanguageListModel)
                        {
                            {

                                Model.UrlsModel = Model.UrlsModelList.FirstOrDefault(d => d.LanguageId == _model.Id);
                                if (Model.UrlsModel == null)
                                {
                                    var urls = new WebCompany.Data.UrlsDto();
                                    urls.ContentId = Model.UrlsModelList.FirstOrDefault().ContentId;
                                    urls.LanguageId = _model.Id;
                                    Model.UrlsModel = urls;
                                }
                            }
                            <div class="tab-pane @(Model.LanguageListModel.IndexOf(_model)==0?"active":"")" id="@(_model.Symbol)" role="tabpanel" aria-labelledby="@(_model.Symbol)-tab">

                                @Html.Partial("_CreateOrEdit", Model)
                            </div>

                        }
                    </div>
                </div>
            </div>

        </div>
    </div>

</div>

WebCompany.UI/Areas/Admin/Views/Urls/List.cshtml
@model  WebCompany.UI.Models.SiteModel

@{
    ViewBag.Title = "Menü Url Listesi";
} 

<style>
    .validation-summary-errors {
        background-color: #D9FFB2;
        border: 1px solid #5CBA30;
        width: 400px;
    }
</style> 
<div class="span9" id="content">

    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Url Listesi</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <div class="table-toolbar">
                        <div class="btn-group">
                            <a href="@WebCompany.Core.UrlService.AdminGetUrl("Urls/Create")">
                                <button class="btn btn-success">Url Ekle  <i class="icon-plus icon-white"></i></button>
                            </a>
                        </div> 
                    </div> 
                    @if (TempData["Message"] != null)
                     {<div class="@Html.Raw(Convert.ToBoolean(TempData["Result"])==true? "alert alert-success":"alert alert-error")">
                        <button class="close" data-dismiss="alert">×</button>
                        <strong>@Html.Raw(Convert.ToBoolean(TempData["Result"]) == true ? "Success!" : "Error!")</strong>@TempData["Message"]
                    </div>}
                  
                    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example2">
                        <thead>
                            <tr>
                                <th>Başlık</th>
                                <th>Url</th> 
                                <th>Durum</th>
                                <th>İşlem</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var Item in Model.UrlsModelList.Where(f=> f.LanguageId==1).OrderBy(x=> x.Id))
                            {
                                <tr class="odd gradeX">
                                    <td>@Item.Title</td> 
                                    <td>@Item.Url</td>
                                    <td>@Html.Raw(Item.Actived == true ? "<span class='label label-success'>Onayli</span>" : "<span class='label label-important'>Onaysız</span>")</td>
                                    <td class="center" style="width:75px;">
                                        @if(Item.Type)
                                        { 
                                        <a href="@WebCompany.Core.UrlService.AdminGetUrl("urls/delete/"+@Item.Id)" class="btn btn-danger btn-mini">Sil</a>
                                        <a href="@WebCompany.Core.UrlService.AdminGetUrl("urls/edit/"+@Item.ContentId)" class="btn btn-success btn-mini">Düzelt</a>
                                        }
                                    </td>

                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
</div>

WebCompany.UI/Areas/Admin/Views/Urls/_CreateOrEdit.cshtml
@model WebCompany.UI.Models.SiteModel

@{
    /**/

    ViewBag.Title = "Menu Url";
}


@using (Html.BeginForm("Save", "Urls", FormMethod.Post, new { id = "frmSite", @class = "form-horizontal", enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary()
    <fieldset>

        @if (Model == null || Model?.UrlsModel?.Id == null)
        {
            <div class="controls">@Html.HiddenFor(m => m.UrlsModel.Id, new { @class = "input-xlarge focused", @readonly = "readonly", Value = "0" })</div>
        }
        else
        {
            <div class="controls">@Html.HiddenFor(m => m.UrlsModel.Id, new { @class = "input-xlarge focused", @readonly = "readonly" })</div>
        }


        <div class="control-group">
            <label class="control-label" for="focusedInput">@Html.LabelFor(m => m.UrlsModel.Title)</label>
            <div class="controls">@Html.TextBoxFor(m => m.UrlsModel.Title, new { @class = "input-xlarge focused", @placeholder = "Başlık..." })  </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="focusedInput">@Html.LabelFor(m => m.UrlsModel.Url)</label>
            @if (Model.UrlsModel.Type)
            {
                <div class="controls">@Html.TextBoxFor(m => m.UrlsModel.Url, new { @class = "input-xlarge focused", @placeholder = "Başlık..." })  </div>

            }
            else
            {
                <div class="controls">@Html.TextBoxFor(m => m.UrlsModel.Url, new { @class = "input-xlarge focused", @readoyly = "true", @placeholder = "Başlık..." })  </div>

            }
        </div>

        @Html.HiddenFor(f => f.UrlsModel.LanguageId)
        @Html.HiddenFor(f => f.UrlsModel.ContentId)
        <div class="control-group">
            <label class="control-label" for="focusedInput">@Html.LabelFor(m => m.UrlsModel.Actived)</label>
            <div class="controls">@Html.CheckBox("UrlsModel.Actived") </div>
        </div>



        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Kaydet</button>
            <button type="reset" class="btn">Vazgeç</button>
        </div>
    </fieldset>
}

               